{
 "title": "AMIRIS Comparison ENTSO-E",
 "time": { "from": "2019-02-02T03:02:29.229Z", "to": "2019-02-24T12:02:49.413Z" },
 "templating": {
  "list": [
   {
    "name": "scenario",
    "query": "select schema_name\nfrom information_schema.schemata\nwhere schema_name like 'amiris_%'"
   },
   {
    "name": "scenario_pretty",
    "query": "Germany 2019, Austria 2019, Simple"
   },
   { "name": "country_benchmark", "query": "DE_LU, AT" }
  ]
 },
 "panels": [
  {
   "title": "Electricity Generation Renewable",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Wind",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(index,1h),\n  wind_offshore AS \"ENTSO-E Offshore\",\n  wind_onshore AS \"ENTSO-E Onshore\"\nFROM entsoe.query_generation\nWHERE\n  $__timeFilter(index) AND\n  country = '$country_benchmark'\nORDER BY 1"
    },
    {
     "rawSql": "select \n$__timeGroupAlias(a.\"time\",$__interval),\nsum(\"ASSUME Actual dispatch\") as \"ASSUME Actual dispatch\", \nsum(\"AMIRIS Awarded Energy\") as \"AMIRIS Awarded Energy\",\n--sum(\"AMIRIS Awarded Energy\"- \"ASSUME Actual dispatch\") as \"Difference\", \n--a.\"agent\",\nc.\"technology\"\nfrom\n(SELECT\n  index as \"time\",\n  avg(power) AS \"ASSUME Actual dispatch\",\n  SUBSTRING(unit,27) as \"agent\",\n  simulation,\n  unit\nFROM unit_dispatch\nWHERE\n  $__timeFilter(index) AND\n  LOWER(simulation) = '$scenario' AND\n  unit like 'VariableRenewableOperator_%'\nGROUP BY 1, unit, power, simulation\nORDER BY 1) a\njoin (SELECT\n  \"TimeStep\" as \"time\",\n  \"AgentId\"::text as \"agent\",\n  avg(\"AwardedEnergyInMWH\") as \"AMIRIS Awarded Energy\"\n  --avg(\"OfferedEnergyInMWH\"*1e3) as \"OfferedEnergyInMWH\",\n  --avg(\"ReceivedMoneyInEUR\") as \"ReceivedMoneyInEUR\",\n  --avg(\"VariableCostsInEUR\") as \"VariableCostsInEUR\"\nFROM $scenario.VariableRenewableOperator\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1, \"agent\"\nORDER BY 1) b on a.agent=b.agent and a.time=b.time\njoin power_plant_meta c on a.unit = c.index and c.simulation=a.simulation\nwhere c.technology like '%wind%'\nGROUP BY 1, c.technology"
    }
   ]
  },
  {
   "title": "Solar",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(index,$__interval),\n  avg(solar) AS \"ENTSO-E Data\"\nFROM entsoe.query_generation\nWHERE\n  $__timeFilter(index) AND\n  country = '$country_benchmark'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "select \n$__timeGroupAlias(a.\"time\",$__interval),\nsum(\"ASSUME Actual dispatch\") as \"ASSUME Actual dispatch\", \nsum(\"AMIRIS Awarded Energy\") as \"AMIRIS Awarded Energy\",\n--sum(\"AMIRIS Awarded Energy\"- \"ASSUME Actual dispatch\") as \"Difference\", \nc.\"technology\"\nfrom\n(SELECT\n  $__timeGroupAlias(index,$__interval),\n  avg(power) AS \"ASSUME Actual dispatch\",\n  SUBSTRING(unit,27) as \"agent\",\n  simulation,\n  unit\nFROM unit_dispatch\nWHERE\n  $__timeFilter(index) AND\n  LOWER(simulation) = '$scenario' AND\n  unit like 'VariableRenewableOperator_%'\nGROUP BY 1, unit, power, simulation\nORDER BY 1) a\njoin (SELECT\n  $__timeGroupAlias(\"TimeStep\",$__interval),\n  \"AgentId\"::text as \"agent\",\n  avg(\"AwardedEnergyInMWH\") as \"AMIRIS Awarded Energy\"\n  --avg(\"OfferedEnergyInMWH\"*1e3) as \"OfferedEnergyInMWH\",\n  --avg(\"ReceivedMoneyInEUR\") as \"ReceivedMoneyInEUR\",\n  --avg(\"VariableCostsInEUR\") as \"VariableCostsInEUR\"\nFROM $scenario.VariableRenewableOperator\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1, \"agent\"\nORDER BY 1) b on a.agent=b.agent and a.time=b.time\njoin power_plant_meta c on a.unit = c.index and c.simulation=a.simulation\nwhere c.technology = 'solar'\nGROUP BY 1, c.technology"
    }
   ]
  },
  {
   "title": "Biogas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(index,$__interval),\n  \"biomass\" AS \"ENTSO-E Data\"\nFROM entsoe.query_generation\nWHERE\n  $__timeFilter(index) AND\n  country = '$country_benchmark'\nORDER BY 1"
    },
    {
     "rawSql": "select \n$__timeGroupAlias(a.\"time\",$__interval),\navg(\"ASSUME Actual dispatch\") as \"ASSUME Actual dispatch\", \navg(\"AMIRIS Awarded Energy\") as \"AMIRIS Awarded Energy\",\n--sum(\"AMIRIS Awarded Energy\"- \"ASSUME Actual dispatch\") as \"Difference\", \n--a.\"agent\",\nc.\"technology\"\nfrom\n(SELECT\n  index as \"time\",\n  avg(power) AS \"ASSUME Actual dispatch\",\n  SUBSTRING(unit,27) as \"agent\",\n  simulation,\n  unit\nFROM unit_dispatch\nWHERE\n  $__timeFilter(index) AND\n  LOWER(simulation) = '$scenario' AND\n  unit like 'VariableRenewableOperator_%'\nGROUP BY 1, unit, power, simulation\nORDER BY 1) a\njoin (SELECT\n  \"TimeStep\" as \"time\",\n  \"AgentId\"::text as \"agent\",\n  avg(\"AwardedEnergyInMWH\") as \"AMIRIS Awarded Energy\"\n  --avg(\"OfferedEnergyInMWH\"*1e3) as \"OfferedEnergyInMWH\",\n  --avg(\"ReceivedMoneyInEUR\") as \"ReceivedMoneyInEUR\",\n  --avg(\"VariableCostsInEUR\") as \"VariableCostsInEUR\"\nFROM $scenario.Biogas\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1, \"agent\"\nORDER BY 1) b on a.agent=b.agent and a.time=b.time\njoin power_plant_meta c on a.unit = c.index and c.simulation=a.simulation\nwhere c.technology = 'biomass'\nGROUP BY 1, c.technology"
    }
   ]
  },
  {
   "title": "Hydro",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(index,$__interval),\n  (\"hydro_run-of-river_and_poundage\"+hydro_water_reservoir) AS \"ENTSO-E Data\"\nFROM entsoe.query_generation\nWHERE\n  $__timeFilter(index) AND\n  country = '$country_benchmark'\nORDER BY 1"
    },
    {
     "rawSql": "select \n$__timeGroupAlias(a.\"time\",$__interval),\navg(\"ASSUME Actual dispatch\") as \"ASSUME Actual dispatch\", \navg(\"AMIRIS Awarded Energy\") as \"AMIRIS Awarded Energy\",\n--avg(\"AMIRIS Awarded Energy\"- \"ASSUME Actual dispatch\") as \"Difference\", \n--a.\"agent\",\nc.\"technology\"\nfrom\n(SELECT\n  index as \"time\",\n  avg(power) AS \"ASSUME Actual dispatch\",\n  SUBSTRING(unit,27) as \"agent\",\n  simulation,\n  unit\nFROM unit_dispatch\nWHERE\n  $__timeFilter(index) AND\n  LOWER(simulation) = '$scenario' AND\n  unit like 'VariableRenewableOperator_%'\nGROUP BY 1, unit, power, simulation\nORDER BY 1) a\njoin (SELECT\n  \"TimeStep\" as \"time\",\n  \"AgentId\"::text as \"agent\",\n  avg(\"AwardedEnergyInMWH\") as \"AMIRIS Awarded Energy\"\n  --avg(\"OfferedEnergyInMWH\"*1e3) as \"OfferedEnergyInMWH\",\n  --avg(\"ReceivedMoneyInEUR\") as \"ReceivedMoneyInEUR\",\n  --avg(\"VariableCostsInEUR\") as \"VariableCostsInEUR\"\nFROM $scenario.VariableRenewableOperator\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1, \"agent\"\nORDER BY 1) b on a.agent=b.agent and a.time=b.time\njoin power_plant_meta c on a.unit = c.index and c.simulation=a.simulation\nwhere c.technology = 'hydro'\nGROUP BY 1, c.technology"
    }
   ]
  },
  {
   "title": "Electricity Generation Conventional",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lignite",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "megwatt" } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(index,1h),\n  (\"fossil_brown_coal/lignite\") AS \"ENTSO-E Data\"\nFROM entsoe.query_generation\nWHERE\n  $__timeFilter(index) AND\n  country = '$country_benchmark'\nORDER BY 1"
      },
      {
       "rawSql": "select a.\"time\",\navg(\"ASSUME Actual dispatch\") as \"ASSUME Actual dispatch\", \navg(\"AMIRIS Awarded Energy\") as \"AMIRIS Awarded Energy\",\navg(\"AMIRIS Awarded Energy\"- \"ASSUME Actual dispatch\") as \"Difference\",\na.technology\nfrom\n(select\ntime,\nsum(\"ASSUME Actual dispatch\") as \"ASSUME Actual dispatch\",\nSUBSTRING(unit,27,1) as \"agent\",\nc.simulation,\nc.technology\nfrom\n(\nSELECT\n  $__timeGroupAlias(index,$__interval),\n  avg(power) AS \"ASSUME Actual dispatch\",\n  unit,\n  simulation\nFROM unit_dispatch\nWHERE\n  $__timeFilter(index) AND\n  LOWER(simulation) = '$scenario' AND\n  unit like 'PredefinedPlantBuilder_200%'\nGROUP BY 1, unit, power, simulation\nORDER BY 1\n) q\njoin power_plant_meta c on q.unit = c.index and c.simulation=q.simulation\ngroup by 1, agent, c.technology, c.simulation) a\njoin (SELECT\n  $__timeGroupAlias(\"TimeStep\",$__interval),\n  substring(\"AgentId\"::text,3) as \"agent\",\n  avg(\"AwardedEnergyInMWH\") as \"AMIRIS Awarded Energy\"\n  --avg(\"OfferedEnergyInMWH\"*1e3) as \"OfferedEnergyInMWH\",\n  --avg(\"ReceivedMoneyInEUR\") as \"ReceivedMoneyInEUR\",\n  --avg(\"VariableCostsInEUR\") as \"VariableCostsInEUR\"\nFROM $scenario.ConventionalPlantOperator\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1, \"agent\"\nORDER BY 1) b on a.agent=b.agent and a.time=b.time\nwhere a.technology = 'lignite'\nGROUP BY 1, a.agent, a.technology\n"
      }
     ]
    },
    {
     "title": "Nuclear",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "megwatt" } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(index,1h),\n  nuclear AS \"ENTSO-E Data\"\nFROM entsoe.query_generation\nWHERE\n  $__timeFilter(index) AND\n  country = '$country_benchmark'\nORDER BY 1"
      },
      {
       "rawSql": "select a.\"time\",\navg(\"ASSUME Actual dispatch\") as \"ASSUME Actual dispatch\", \navg(\"AMIRIS Awarded Energy\") as \"AMIRIS Awarded Energy\",\navg(\"AMIRIS Awarded Energy\"- \"ASSUME Actual dispatch\") as \"Difference\",\na.technology\nfrom\n(select\ntime,\nsum(\"ASSUME Actual dispatch\") as \"ASSUME Actual dispatch\",\nSUBSTRING(unit,27,1) as \"agent\",\nc.simulation,\nc.technology\nfrom\n(\nSELECT\n  $__timeGroupAlias(index,$__interval),\n  avg(power) AS \"ASSUME Actual dispatch\",\n  unit,\n  simulation\nFROM unit_dispatch\nWHERE\n  $__timeFilter(index) AND\n  LOWER(simulation) = '$scenario' AND\n  unit like 'PredefinedPlantBuilder_200%'\nGROUP BY 1, unit, power, simulation\nORDER BY 1\n) q\njoin power_plant_meta c on q.unit = c.index and c.simulation=q.simulation\nwhere c.technology = 'nuclear'\ngroup by 1, agent, c.technology, c.simulation) a\njoin (SELECT\n  $__timeGroupAlias(\"TimeStep\",$__interval),\n  substring(\"AgentId\"::text,3) as \"agent\",\n  avg(\"AwardedEnergyInMWH\") as \"AMIRIS Awarded Energy\"\n  --avg(\"OfferedEnergyInMWH\"*1e3) as \"OfferedEnergyInMWH\",\n  --avg(\"ReceivedMoneyInEUR\") as \"ReceivedMoneyInEUR\",\n  --avg(\"VariableCostsInEUR\") as \"VariableCostsInEUR\"\nFROM $scenario.ConventionalPlantOperator\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1, \"agent\"\nORDER BY 1) b on a.agent=b.agent and a.time=b.time\n\nGROUP BY 1, a.agent, a.technology"
      }
     ]
    },
    {
     "title": "Oil",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "megwatt" } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(index,1h),\n  fossil_oil AS \"ENTSO-E Data\"\nFROM entsoe.query_generation\nWHERE\n  $__timeFilter(index) AND\n  country = '$country_benchmark'\nORDER BY 1"
      },
      {
       "rawSql": "select a.\"time\",\navg(\"ASSUME Actual dispatch\") as \"ASSUME Actual dispatch\", \navg(\"AMIRIS Awarded Energy\") as \"AMIRIS Awarded Energy\",\navg(\"AMIRIS Awarded Energy\"- \"ASSUME Actual dispatch\") as \"Difference\",\na.technology\nfrom\n(select\ntime,\nsum(\"ASSUME Actual dispatch\") as \"ASSUME Actual dispatch\",\nSUBSTRING(unit,27,1) as \"agent\",\nc.simulation,\nc.technology\nfrom\n(\nSELECT\n  $__timeGroupAlias(index,$__interval),\n  avg(power) AS \"ASSUME Actual dispatch\",\n  unit,\n  simulation\nFROM unit_dispatch\nWHERE\n  $__timeFilter(index) AND\n  LOWER(simulation) = '$scenario' AND\n  unit like 'PredefinedPlantBuilder_200%'\nGROUP BY 1, unit, power, simulation\nORDER BY 1\n) q\njoin power_plant_meta c on q.unit = c.index and c.simulation=q.simulation\nwhere c.technology = 'oil'\ngroup by 1, agent, c.technology, c.simulation) a\njoin (SELECT\n  $__timeGroupAlias(\"TimeStep\",$__interval),\n  substring(\"AgentId\"::text,3) as \"agent\",\n  avg(\"AwardedEnergyInMWH\") as \"AMIRIS Awarded Energy\"\n  --avg(\"OfferedEnergyInMWH\"*1e3) as \"OfferedEnergyInMWH\",\n  --avg(\"ReceivedMoneyInEUR\") as \"ReceivedMoneyInEUR\",\n  --avg(\"VariableCostsInEUR\") as \"VariableCostsInEUR\"\nFROM $scenario.ConventionalPlantOperator\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1, \"agent\"\nORDER BY 1) b on a.agent=b.agent and a.time=b.time\n\nGROUP BY 1, a.agent, a.technology"
      }
     ]
    },
    {
     "title": "Hard Coal",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "megwatt" } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(index,1h),\n  fossil_hard_coal AS \"ENTSO-E Data\"\nFROM entsoe.query_generation\nWHERE\n  $__timeFilter(index) AND\n  country = '$country_benchmark'\nORDER BY 1"
      },
      {
       "rawSql": "select a.\"time\",\navg(\"ASSUME Actual dispatch\") as \"ASSUME Actual dispatch\", \navg(\"AMIRIS Awarded Energy\") as \"AMIRIS Awarded Energy\",\navg(\"AMIRIS Awarded Energy\"- \"ASSUME Actual dispatch\") as \"Difference\",\na.technology\nfrom\n(select\ntime,\nsum(\"ASSUME Actual dispatch\") as \"ASSUME Actual dispatch\",\nSUBSTRING(unit,27,1) as \"agent\",\nc.simulation,\nc.technology\nfrom\n(\nSELECT\n  $__timeGroupAlias(index,$__interval),\n  avg(power) AS \"ASSUME Actual dispatch\",\n  unit,\n  simulation\nFROM unit_dispatch\nWHERE\n  $__timeFilter(index) AND\n  LOWER(simulation) = '$scenario' AND\n  unit like 'PredefinedPlantBuilder_200%'\nGROUP BY 1, unit, power, simulation\nORDER BY 1\n) q\njoin power_plant_meta c on q.unit = c.index and c.simulation=q.simulation\nwhere c.technology = 'hard coal'\ngroup by 1, agent, c.technology, c.simulation) a\njoin (SELECT\n  $__timeGroupAlias(\"TimeStep\",$__interval),\n  substring(\"AgentId\"::text,3) as \"agent\",\n  avg(\"AwardedEnergyInMWH\") as \"AMIRIS Awarded Energy\"\n  --avg(\"OfferedEnergyInMWH\"*1e3) as \"OfferedEnergyInMWH\",\n  --avg(\"ReceivedMoneyInEUR\") as \"ReceivedMoneyInEUR\",\n  --avg(\"VariableCostsInEUR\") as \"VariableCostsInEUR\"\nFROM $scenario.ConventionalPlantOperator\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1, \"agent\"\nORDER BY 1) b on a.agent=b.agent and a.time=b.time\n\nGROUP BY 1, a.agent, a.technology"
      }
     ]
    },
    {
     "title": "Natural Gas",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "megwatt" } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(index,1h),\n  fossil_gas AS \"ENTSO-E Data\"\nFROM entsoe.query_generation\nWHERE\n  $__timeFilter(index) AND\n  country = '$country_benchmark'\nORDER BY 1"
      },
      {
       "rawSql": "select a.\"time\",\navg(\"ASSUME Actual dispatch\") as \"ASSUME Actual dispatch\", \navg(\"AMIRIS Awarded Energy\") as \"AMIRIS Awarded Energy\",\navg(\"AMIRIS Awarded Energy\"- \"ASSUME Actual dispatch\") as \"Difference\",\na.technology\nfrom\n(select\ntime,\nsum(\"ASSUME Actual dispatch\") as \"ASSUME Actual dispatch\",\nSUBSTRING(unit,27,1) as \"agent\",\nc.simulation,\nc.technology\nfrom\n(\nSELECT\n  $__timeGroupAlias(index,$__interval),\n  avg(power) AS \"ASSUME Actual dispatch\",\n  unit,\n  simulation\nFROM unit_dispatch\nWHERE\n  $__timeFilter(index) AND\n  LOWER(simulation) = '$scenario' AND\n  unit like 'PredefinedPlantBuilder_200%'\nGROUP BY 1, unit, power, simulation\nORDER BY 1\n) q\njoin power_plant_meta c on q.unit = c.index and c.simulation=q.simulation\nwhere c.technology = 'natural gas'\ngroup by 1, agent, c.technology, c.simulation) a\njoin (SELECT\n  $__timeGroupAlias(\"TimeStep\",$__interval),\n  substring(\"AgentId\"::text,3) as \"agent\",\n  avg(\"AwardedEnergyInMWH\") as \"AMIRIS Awarded Energy\"\n  --avg(\"OfferedEnergyInMWH\"*1e3) as \"OfferedEnergyInMWH\",\n  --avg(\"ReceivedMoneyInEUR\") as \"ReceivedMoneyInEUR\",\n  --avg(\"VariableCostsInEUR\") as \"VariableCostsInEUR\"\nFROM $scenario.ConventionalPlantOperator\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1, \"agent\"\nORDER BY 1) b on a.agent=b.agent and a.time=b.time\n\nGROUP BY 1, a.agent, a.technology"
      }
     ]
    },
    {
     "title": "StorageTrader",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "megwatt" } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(\"TimeStep\",$__interval),\n  --\"AgentId\"::text as \"agent\",\n  --avg(\"AwardedEnergyInMWH\"*1e3) as \"AwardedEnergyInMWH\",\n  --avg(\"OfferedEnergyInMWH\"*1e3) as \"OfferedEnergyInMWH\",\n  --avg(\"OfferedChargePriceInEURperMWH\") as \"OfferedChargePriceInEURperMWH\",\n  --avg(\"OfferedDischargePriceInEURperMWH\") as \"OfferedDischargePriceInEURperMWH\",\n  avg(\"AwardedDischargeEnergyInMWH\")-avg(\"AwardedChargeEnergyInMWH\") as \"AMIRIS Storage Dispatch\",\n  avg(\"StoredEnergyInMWH\")*1e3 as \"AMIRIS StoredEnergyInMWH\"\nFROM $scenario.StorageTrader\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1\nORDER BY 1\n"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(index,$__interval),\n  soc AS \"State of Charge\"\nFROM unit_dispatch\nWHERE\n  $__timeFilter(index) AND\n  simulation = '$scenario' and\n  unit like 'StorageTrader%'\nGROUP BY 1, SOC\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(index,1h),\n  hydro_pumped_storage AS \"ENTSO-E Data\"\nFROM entsoe.query_generation\nWHERE\n  $__timeFilter(index) AND\n  country = '$country_benchmark'\nORDER BY 1"
      }
     ]
    },
    {
     "title": "ENTSO-E Comparison",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "kwatt" } },
     "targets": [
      {
       "rawSql": "SELECT\n  index AS \"time\",\n  (biomass+solar+\"fossil_gas\"+\"fossil_brown_coal/lignite\"+\"fossil_oil\"+\"fossil_hard_coal\"+geothermal+other+waste+\"wind_offshore\"+\"wind_onshore\"+nuclear)*1e3 as total_entsoe\nFROM entsoe.query_generation\nWHERE\n  $__timeFilter(index) AND\n  country = 'DE'\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  index AS \"time\",\n  nuclear*1e3 as nuclear,\n  \"fossil_hard_coal\"*1e3 as coal,\n  (\"hydro_run-of-river_and_poundage\"+hydro_water_reservoir)*1e3 as water,\n  biomass*1e3 as bio,\n  (\"fossil_coal-derived_gas\"+\"fossil_gas\")*1e3 as gas,\n  (fossil_oil+coalesce(fossil_oil_shale,0)+coalesce(fossil_peat,0)+\"fossil_brown_coal/lignite\")*1e3 as lignite,\n  (\"wind_offshore\"+\"wind_onshore\")*1e3 as wind,\n  solar*1e3 as solar,\n  (geothermal+other+waste)*1e3 as others\nFROM entsoe.query_generation\nWHERE\n  $__timeFilter(index) AND\n  country = 'DE'\nORDER BY 1"
      }
     ]
    },
    {
     "title": "ENTSOE Mix",
     "type": "piechart",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "megwatt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  index AS \"time\",\n  biomass,\n  \"fossil_brown_coal/lignite\",\n  \"fossil_coal-derived_gas\",\n  fossil_gas,\n  fossil_hard_coal,\n  fossil_oil,\n  fossil_oil_shale,\n  fossil_peat,\n  geothermal,\n  hydro_pumped_storage,\n  \"hydro_run-of-river_and_poundage\",\n  nuclear,\n  wind_offshore,\n  wind_onshore,\n  solar\nFROM query_installed_generation_capacity\nWHERE\n  country = 'DE'\nORDER BY 1"
      }
     ]
    }
   ]
  },
  { "title": "Comparison View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "${scenario_pretty} Market Price",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "€/MWh" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(index,$__interval),\n  avg(\"0\") AS \"ENTSO-E price\"\nFROM query_day_ahead_prices\nWHERE\n  $__timeFilter(index) AND\n  country = '$country_benchmark'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"product_start\",$__interval),\n  avg(price) AS \"ASSUME Price\"\nFROM market_meta\nWHERE (\"simulation\" LIKE '$scenario') AND market_id = 'Market_1' AND $__timeFilter(product_start)\nGROUP BY market_id, simulation, product_start\nORDER BY 1;\n"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"TimeStep\",$__interval),\n  avg(\"ElectricityPriceInEURperMWH\") as \"AMIRIS Price\"\nFROM $scenario.DayAheadMarketSingleZone\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "${scenario_pretty} Demand",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(index,$__interval),\n  avg(actual_load) AS \"Historical Demand\"\nFROM query_load\nWHERE\n  $__timeFilter(index) AND\n  country = '$country_benchmark'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(datetime,$__interval),\n  -avg(power) AS \"ASSUME Market Dispatch\"\nFROM market_dispatch\nWHERE\n  $__timeFilter(datetime) AND\n  LOWER(simulation) = '$scenario' AND\n  unit_id = 'demand_100_0'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"TimeStep\",$__interval),\n  avg(\"AwardedEnergyInMWH\") as \"AMIRIS Market Dispatch\"\nFROM $scenario.demandtrader\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(index, $__interval),\n  avg(\n    biomass + solar + \"fossil_gas\" + coalesce(\"fossil_brown_coal/lignite\",0) + coalesce(\"fossil_oil\",0) + \"fossil_hard_coal\" + geothermal + other + waste + coalesce(\"wind_offshore\",0) + \"wind_onshore\" + coalesce(nuclear,0)\n  ) as \"ENTSO-E Generation\"\nFROM\n  query_generation\nWHERE\n  $__timeFilter(index)\n  AND country = '$country_benchmark'\nGROUP BY\n  1\nORDER BY\n  1"
    }
   ]
  },
  {
   "title": "${scenario_pretty} Renewable Unitwise Dispatch",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "select \n$__timeGroupAlias(a.\"time\",$__interval),\navg(\"ASSUME Actual dispatch\") as \"ASSUME Actual dispatch\", \navg(\"AMIRIS Awarded Energy\") as \"AMIRIS Awarded Energy\",\navg(\"AMIRIS Awarded Energy\"- \"ASSUME Actual dispatch\") as \"Difference\", \na.\"agent\"\nfrom\n(SELECT\n  index as \"time\",\n  avg(power) AS \"ASSUME Actual dispatch\",\n  SUBSTRING(unit,27) as \"agent\"\nFROM unit_dispatch\nWHERE\n  $__timeFilter(index) AND\n  LOWER(simulation) = '$scenario' AND\n  unit like 'VariableRenewableOperator_%'\nGROUP BY 1, unit, power\nORDER BY 1) a\njoin (SELECT\n  \"TimeStep\" as \"time\",\n  \"AgentId\"::text as \"agent\",\n  avg(\"AwardedEnergyInMWH\") as \"AMIRIS Awarded Energy\"\n  --avg(\"OfferedEnergyInMWH\"*1e3) as \"OfferedEnergyInMWH\",\n  --avg(\"ReceivedMoneyInEUR\") as \"ReceivedMoneyInEUR\",\n  --avg(\"VariableCostsInEUR\") as \"VariableCostsInEUR\"\nFROM $scenario.VariableRenewableOperator\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1, \"agent\"\nORDER BY 1) b on a.agent=b.agent and a.time=b.time\n--where a.agent = '10'\nGROUP BY 1, a.\"agent\""
    }
   ]
  },
  {
   "title": "${scenario_pretty} Conventional",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "select \"ASSUME Actual dispatch\", \n\"AMIRIS Awarded Energy\",\n\"AMIRIS Awarded Energy\"- \"ASSUME Actual dispatch\" as \"Difference\", \na.\"time\", a.\"agent\"\nfrom\n(select\ntime,\nsum(\"ASSUME Actual dispatch\") as \"ASSUME Actual dispatch\",\nSUBSTRING(unit,27,1) as \"agent\"\nfrom\n(\nSELECT\n  $__timeGroupAlias(index,$__interval),\n  avg(power) AS \"ASSUME Actual dispatch\",\n  unit\nFROM unit_dispatch\nWHERE\n  $__timeFilter(index) AND\n  LOWER(simulation) = '$scenario' AND\n  unit like 'PredefinedPlantBuilder_200%'\nGROUP BY 1, unit, power\nORDER BY 1\n) q\ngroup by 1, agent) a\njoin (SELECT\n  $__timeGroupAlias(\"TimeStep\",$__interval),\n  substring(\"AgentId\"::text,3) as \"agent\",\n  avg(\"AwardedEnergyInMWH\") as \"AMIRIS Awarded Energy\"\n  --avg(\"OfferedEnergyInMWH\"*1e3) as \"OfferedEnergyInMWH\",\n  --avg(\"ReceivedMoneyInEUR\") as \"ReceivedMoneyInEUR\",\n  --avg(\"VariableCostsInEUR\") as \"VariableCostsInEUR\"\nFROM $scenario.ConventionalPlantOperator\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1, \"agent\"\nORDER BY 1) b on a.agent=b.agent and a.time=b.time"
    }
   ]
  },
  {
   "title": "Detail Views - Left ASSUME - Right AMIRIS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 }
  },
  {
   "title": "Market Summary ASSUME",
   "type": "timeseries",
   "description": "Overview of market results for the chossen market",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "repeat": "market",
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  product_start AS \"time\",\n  avg(demand_volume)*1e3 AS \"Demand volume\",\n  avg(price) AS \"Price\",\n  avg(supply_volume)*1e3 AS \"Supply volume\"\nFROM market_meta\nWHERE (\"simulation\" LIKE '$scenario') AND market_id = 'Market_1' AND $__timeFilter(product_start)\nGROUP BY market_id, simulation, product_start\nORDER BY 1;\n"
    }
   ]
  },
  {
   "title": "${scenario_pretty} Conventional",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "select\ntime,\nsum(\"ASSUME Actual dispatch\") as \"ASSUME Actual dispatch\",\nSUBSTRING(unit,27,1) as \"agent\",\nSUBSTRING(unit,29) as \"nr\"\nfrom\n(\nSELECT\n  $__timeGroupAlias(index,$__interval),\n  avg(power) AS \"ASSUME Actual dispatch\",\n  unit\nFROM unit_dispatch\nWHERE\n  $__timeFilter(index) AND\n  LOWER(simulation) = '$scenario' AND\n  unit like 'PredefinedPlantBuilder_200%'\nGROUP BY 1, unit, power\nORDER BY 1\n) q\nwhere SUBSTRING(unit,27,1)='1'\ngroup by 1, agent, nr"
    }
   ]
  },
  {
   "title": "Unitwise Dispatch",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(datetime,$__interval),\n  power AS \"Market dispatch\",\n  concat(unit_id, ' - ', market_id) as \"unit_id\"\nFROM market_dispatch\nWHERE\n  $__timeFilter(datetime) AND\n  LOWER(simulation) = '$scenario' AND\n  unit_id = 'demand_100_0'\nGROUP BY 1, unit_id, power, market_id\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(index,$__interval),\n  power AS \"Actual dispatch\",\n  unit\nFROM unit_dispatch\nWHERE\n  $__timeFilter(index) AND\n  LOWER(simulation) = '$scenario' AND\n  unit = 'demand_100_0'\nGROUP BY 1, unit, power\nORDER BY 1"
    }
   ]
  },
  {
   "title": "DayAheadMarketSingleZone AMIRIS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"TimeStep\",$__interval),\n  \"AgentId\"::text as \"agent\",\n  avg(\"ElectricityPriceInEURperMWH\") as \"ElectricityPriceInEURperMWH\",\n  avg(\"AwardedEnergyInMWH\"*1e3) as \"AwardedEnergyInMWH\",\n  avg(\"DispatchSystemCostInEUR\") as \"DispatchSystemCostInEUR\"\n  \nFROM $scenario.DayAheadMarketSingleZone\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1, \"agent\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Conventional Unitwise Dispatch",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(datetime,$__interval),\n  left(unit_id, 27) as unit,\n  avg(power) AS \"Market dispatch\"\n  \nFROM market_dispatch\nWHERE\n  $__timeFilter(datetime) AND\n  LOWER(simulation) = '$scenario' AND\n  unit_id like 'PredefinedPlantBuilder_200%'\nGROUP BY 1, unit_id, power\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(index,$__interval),\n  avg(power) AS \"Actual dispatch\",\n  left(unit, 27) as unit\nFROM unit_dispatch\nWHERE\n  $__timeFilter(index) AND\n  LOWER(simulation) = '$scenario' AND\n  unit like 'PredefinedPlantBuilder_200%'\nGROUP BY 1, unit, power\nORDER BY 1"
    }
   ]
  },
  {
   "title": "demandtrader",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"TimeStep\",$__interval),\n  \"AgentId\"::text as \"agent\",\n  -avg(\"RequestedEnergyInMWH\")*1e3 as \"RequestedEnergyInMWH\",\n  -avg(\"AwardedEnergyInMWH\")*1e3 as \"AwardedEnergyInMWH\"\nFROM $scenario.demandtrader\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1, \"agent\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Renewable Unitwise Dispatch",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(datetime,$__interval),\n  avg(power) AS \"Market dispatch\",\n  concat(unit_id, ' - ', market_id) as \"unit_id\"\nFROM market_dispatch\nWHERE\n  $__timeFilter(datetime) AND\n  LOWER(simulation) = '$scenario' AND\n  unit_id like 'VariableRenewableOperator_%'\nGROUP BY 1, unit_id, power, market_id\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(index,$__interval),\n  avg(power) AS \"Actual dispatch\",\n  unit\nFROM unit_dispatch\nWHERE\n  $__timeFilter(index) AND\n  LOWER(simulation) = '$scenario' AND\n  unit like 'VariableRenewableOperator_%'\nGROUP BY 1, unit, power\nORDER BY 1"
    }
   ]
  },
  {
   "title": "ConventionalPlantOperator",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"TimeStep\",$__interval),\n  \"AgentId\"::text as \"agent\",\n  avg(\"AwardedEnergyInMWH\"*1e3) as \"AwardedEnergyInMWH\",\n  avg(\"OfferedEnergyInMWH\"*1e3) as \"OfferedEnergyInMWH\",\n  avg(\"ReceivedMoneyInEUR\") as \"ReceivedMoneyInEUR\",\n  avg(\"VariableCostsInEUR\") as \"VariableCostsInEUR\"\nFROM $scenario.ConventionalPlantOperator\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1, \"agent\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Merit Order Forecaster",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"TimeStep\",$__interval),\n  \"AgentId\"::text as \"agent\",\n  avg(\"AwardedEnergyForecastInMWH\"*1e3) as \"AwardedEnergyForecastInMWH\",\n  avg(\"ElectricityPriceForecastInEURperMWH\") as \"ElectricityPriceForecastInEURperMWH\"\nFROM $scenario.meritorderforecaster\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1, \"agent\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "VariableRenewableOperator",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"TimeStep\",$__interval),\n  \"AgentId\"::text as \"agent\",\n  avg(\"AwardedEnergyInMWH\"*1e3) as \"AwardedEnergyInMWH\",\n  avg(\"OfferedEnergyInMWH\"*1e3) as \"OfferedEnergyInMWH\",\n  --avg(\"ReceivedMoneyInEUR\") as \"ReceivedMoneyInEUR\",\n  avg(\"VariableCostsInEUR\") as \"VariableCostsInEUR\"\nFROM $scenario.VariableRenewableOperator\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1, \"agent\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Additional",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 },
   "collapsed": true,
   "panels": [
    {
     "title": "ConventionalPlantOperator_DispatchedEnergyInMWHperPlant",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 135 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(\"TimeStep\",$__interval),\n  \"AgentId\"::text as \"agent\",\n  \"ID\",\n  avg(\"DispatchedEnergyInMWHperPlant\"*1e3) as \"DispatchedEnergyInMWHperPlant\"\nFROM $scenario.ConventionalPlantOperator_DispatchedEnergyInMWHperPlant\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1, \"agent\", \"ID\"\nORDER BY 1"
      }
     ]
    },
    {
     "title": "StorageTrader",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 135 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(\"TimeStep\",$__interval),\n  \"AgentId\"::text as \"agent\",\n  avg(\"AwardedEnergyInMWH\"*1e3) as \"AwardedEnergyInMWH\",\n  avg(\"OfferedEnergyInMWH\"*1e3) as \"OfferedEnergyInMWH\",\n  avg(\"OfferedChargePriceInEURperMWH\") as \"OfferedChargePriceInEURperMWH\",\n  avg(\"OfferedDischargePriceInEURperMWH\") as \"OfferedDischargePriceInEURperMWH\",\n  avg(\"AwardedChargeEnergyInMWH\"*1e3) as \"AwardedChargeEnergyInMWH\",\n  avg(\"AwardedDischargeEnergyInMWH\"*1e3) as \"AwardedDischargeEnergyInMWH\",\n  avg(\"StoredEnergyInMWH\"*1e3) as \"StoredEnergyInMWH\",\n  avg(\"VariableCostsInEUR\") as \"VariableCostsInEUR\",\n  avg(\"ReceivedMoneyInEUR\") as \"ReceivedMoneyInEUR\"\nFROM $scenario.StorageTrader\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1, \"agent\"\nORDER BY 1\n"
      }
     ]
    },
    {
     "title": "ConventionalPlantOperator_VariableCostsInEURperPlant",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 144 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(\"TimeStep\",$__interval),\n  \"AgentId\"::text as \"agent\",\n  \"ID\",\n  avg(\"VariableCostsInEURperPlant\") as \"VariableCostsInEURperPlant\"\nFROM $scenario.ConventionalPlantOperator_VariableCostsInEURperPlant\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1, \"agent\", \"ID\"\nORDER BY 1"
      }
     ]
    },
    {
     "title": "SystemOperatorTrader",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 144 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(\"TimeStep\",$__interval),\n  \"AgentId\"::text as \"agent\",\n  avg(\"AwardedEnergyInMWH\"*1e3) as \"AwardedEnergyInMWH\",\n  avg(\"OfferedEnergyInMWH\"*1e3) as \"OfferedEnergyInMWH\",\n  avg(\"ReceivedSupportInEUR\") as \"ReceivedSupportInEUR\",\n  avg(\"RefundedSupportInEUR\") as \"RefundedSupportInEUR\",\n  avg(\"ReceivedMarketRevenues\") as \"ReceivedMarketRevenuesInEUR\",\n  avg(\"TrueGenerationPotentialInMWH\"*1e3) as \"TrueGenerationPotentialInMWH\"\nFROM $scenario.SystemOperatorTrader\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1, \"agent\"\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Stromerzeugung $country_benchmark",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 153 },
     "fieldConfig": { "defaults": { "unit": "megwatt" } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(\"index\",$__interval),\n  avg(biomass) as biomass,\n  avg(fossil_hard_coal) as fossil_hard_coal,\n  avg(geothermal) as geothermal,\n  avg(nuclear) as nuclear,\n  avg(\"fossil_brown_coal/lignite\") as \"fossil_brown_coal/lignite\",\n  avg(\"fossil_coal-derived_gas\") as \"fossil_coal-derived_gas\",\n  avg(\"hydro_run-of-river_and_poundage\") as \"hydro_run-of-river_and_poundage\",\n  avg(waste) as waste,\n  avg(solar) as solar,\n  avg(wind_offshore) as wind_offshore,\n  avg(wind_onshore) as wind_onshore,\n  avg(other_renewable) as other_renewable,\n  avg(hydro_water_reservoir) as hydro_water_reservoir,\n  avg(fossil_gas) as fossil_gas\nFROM entsoe.query_generation\nWHERE\n  $__timeFilter(index) AND\n  country = '$country_benchmark'\ngroup by 1\nORDER BY 1,2\n"
      }
     ]
    },
    {
     "title": "ConventionalTrader",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 153 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(\"TimeStep\",$__interval),\n  \"AgentId\"::text as \"agent\",\n  avg(\"AwardedEnergyInMWH\"*1e3) as \"AwardedEnergyInMWH\",\n  avg(\"OfferedEnergyInMWH\"*1e3) as \"OfferedEnergyInMWH\"\nFROM $scenario.ConventionalTrader\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1, \"agent\"\nORDER BY 1"
      }
     ]
    },
    {
     "title": "ConventionalPlantOperator_ReceivedMoneyInEURperPlant",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 162 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(\"TimeStep\",$__interval),\n  \"AgentId\"::text as \"agent\",\n  \"ID\",\n  avg(\"ReceivedMoneyInEURperPlant\") as \"ReceivedMoneyInEURperPlant\"\nFROM $scenario.ConventionalPlantOperator_ReceivedMoneyInEURperPlant\nWHERE\n  $__timeFilter(\"TimeStep\")\nGROUP BY 1, \"agent\", \"ID\"\nORDER BY 1"
      }
     ]
    }
   ]
  }
 ]
}