{
 "title": "ENTSO-E Comparison",
 "time": { "from": "2023-12-30T13:31:59.000Z", "to": "2024-02-13T07:32:39.000Z" },
 "templating": {
  "list": [
   {
    "name": "scenario",
    "query": "SELECT simulation\nFROM market_meta\nwhere simulation like 'amiris_%' or simulation like '%mastr_%'"
   },
   {
    "name": "scenario_pretty",
    "query": "Germany 2019, Austria 2019, Simple"
   },
   { "name": "country_benchmark", "query": "DE_LU, AT, DE_AT_LU" }
  ]
 },
 "panels": [
  { "title": "Comparison View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "${scenario_pretty} Market Price",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "€/MWh" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(index,$__interval),\n  avg(\"0\") AS \"ENTSO-E price\"\nFROM entsoe.query_day_ahead_prices\nWHERE\n  $__timeFilter(index) AND\n  country = '$country_benchmark'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"product_start\",$__interval),\n  avg(price) AS \"ASSUME Price\"\nFROM market_meta\nWHERE (\"simulation\" LIKE '$scenario') AND $__timeFilter(product_start)\nGROUP BY market_id, simulation, product_start\nORDER BY 1;\n"
    }
   ]
  },
  {
   "title": "${scenario_pretty} Demand",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(index,$__interval),\n  avg(actual_load) AS \"Historical Demand\"\nFROM entsoe.query_load\nWHERE\n  $__timeFilter(index) AND\n  country = '$country_benchmark'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(product_start, $__interval),\n  avg(demand_volume) AS \"Demand volume\",\n  node\nFROM market_meta\nWHERE (\"simulation\" LIKE '$scenario') AND $__timeFilter(product_start)\nGROUP BY 1, simulation, node\nORDER BY 1, node;\n"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(index, $__interval),\n  avg(\n    biomass + solar + \"fossil_gas\" + coalesce(\"fossil_brown_coal/lignite\",0) + coalesce(\"fossil_oil\",0) + \"fossil_hard_coal\" + geothermal + other + waste + coalesce(\"wind_offshore\",0) + \"wind_onshore\" + coalesce(nuclear,0)\n  ) as \"ENTSO-E Generation\"\nFROM\n  entsoe.query_generation\nWHERE\n  $__timeFilter(index)\n  AND country = '$country_benchmark'\nGROUP BY\n  1\nORDER BY\n  1"
    }
   ]
  },
  {
   "title": "Market Summary $market",
   "type": "timeseries",
   "description": "Overview of market results for the chossen market",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(product_start, $__interval),\n  avg(demand_volume) AS \"Demand volume\",\n  avg(supply_volume) AS \"Supply volume\",\n  avg(price) AS \"Price\",\n  node\nFROM market_meta\nWHERE (\"simulation\" LIKE '$scenario') AND $__timeFilter(product_start)\nGROUP BY 1, market_id, simulation, node\nORDER BY 1, node;\n"
    }
   ]
  },
  {
   "title": "Electricity Generation Renewable",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }
  },
  {
   "title": "Wind",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(index,1h),\n  wind_offshore+wind_onshore AS \"ENTSO-E Wind\"\n  --wind_onshore AS \"ENTSO-E Onshore\"\nFROM entsoe.query_generation\nWHERE\n  $__timeFilter(index) AND\n  country = '$country_benchmark'\nORDER BY 1"
    },
    {
     "rawSql": "-- select average through time aggregation\nselect \n$__timeGroupAlias(a.\"time\",$__interval),\navg(\"ASSUME Actual dispatch\") as \"ASSUME Actual dispatch\",\ntechnology\nfrom (\nselect \n-- select sum over all units\n$__timeGroupAlias(a.\"time\",'1h'),\nsum(\"ASSUME Actual dispatch\") as \"ASSUME Actual dispatch\",\ntechnology\nfrom\n(\n  -- select average per unit - remove duplicate sent data\n  SELECT\n  $__timeGroupAlias(time,'1h'),\n  avg(power) AS \"ASSUME Actual dispatch\",\n  unit_dispatch.simulation,\n  technology,\n  unit\nFROM unit_dispatch\njoin power_plant_meta c on unit = c.index and c.simulation=unit_dispatch.simulation\nwhere c.technology like '%wind%'\nand\n  $__timeFilter(time) AND\n  LOWER(unit_dispatch.simulation) = '$scenario'\nGROUP BY 1, unit_dispatch.simulation, c.technology, unit\nORDER BY 1) a\nGROUP BY 1, technology\n) a\nGROUP BY 1, technology"
    }
   ]
  },
  {
   "title": "Solar",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(index,$__interval),\n  avg(solar) AS \"ENTSO-E Data\"\nFROM entsoe.query_generation\nWHERE\n  $__timeFilter(index) AND\n  country = '$country_benchmark'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "-- select average through time aggregation\nselect \n$__timeGroupAlias(a.\"time\",$__interval),\navg(\"ASSUME Actual dispatch\") as \"ASSUME Actual dispatch\",\ntechnology\nfrom (\nselect \n-- select sum over all units\n$__timeGroupAlias(a.\"time\",'1h'),\nsum(\"ASSUME Actual dispatch\") as \"ASSUME Actual dispatch\",\ntechnology\nfrom\n(\n  -- select average per unit - remove duplicate sent data\n  SELECT\n  $__timeGroupAlias(time,'1h'),\n  avg(power) AS \"ASSUME Actual dispatch\",\n  unit_dispatch.simulation,\n  technology,\n  unit\nFROM unit_dispatch\njoin power_plant_meta c on unit = c.index and c.simulation=unit_dispatch.simulation\nwhere c.technology = 'solar'\nand\n  $__timeFilter(time) AND\n  LOWER(unit_dispatch.simulation) = '$scenario'\nGROUP BY 1, unit_dispatch.simulation, c.technology, unit\nORDER BY 1) a\nGROUP BY 1, technology\n) a\nGROUP BY 1, technology"
    }
   ]
  },
  {
   "title": "Biogas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(index,$__interval),\n  \"biomass\" AS \"ENTSO-E Data\"\nFROM entsoe.query_generation\nWHERE\n  $__timeFilter(index) AND\n  country = '$country_benchmark'\nORDER BY 1"
    },
    {
     "rawSql": "-- select average through time aggregation\nselect \n$__timeGroupAlias(a.\"time\",$__interval),\navg(\"ASSUME Actual dispatch\") as \"ASSUME Actual dispatch\",\ntechnology\nfrom (\nselect \n-- select sum over all units\n$__timeGroupAlias(a.\"time\",'1h'),\nsum(\"ASSUME Actual dispatch\") as \"ASSUME Actual dispatch\",\ntechnology\nfrom\n(\n  -- select average per unit - remove duplicate sent data\n  SELECT\n  $__timeGroupAlias(time,'1h'),\n  avg(power) AS \"ASSUME Actual dispatch\",\n  unit_dispatch.simulation,\n  technology,\n  unit\nFROM unit_dispatch\njoin power_plant_meta c on unit = c.index and c.simulation=unit_dispatch.simulation\nwhere c.technology = 'biomass'\nand\n  $__timeFilter(time) AND\n  LOWER(unit_dispatch.simulation) = '$scenario'\nGROUP BY 1, unit_dispatch.simulation, c.technology, unit\nORDER BY 1) a\nGROUP BY 1, technology\n) a\nGROUP BY 1, technology"
    }
   ]
  },
  {
   "title": "Hydro",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(index,$__interval),\n  (\"hydro_run-of-river_and_poundage\"+hydro_water_reservoir) AS \"ENTSO-E Data\"\nFROM entsoe.query_generation\nWHERE\n  $__timeFilter(index) AND\n  country = '$country_benchmark'\nORDER BY 1"
    },
    {
     "rawSql": "-- select average through time aggregation\nselect \n$__timeGroupAlias(a.\"time\",$__interval),\navg(\"ASSUME Actual dispatch\") as \"ASSUME Actual dispatch\",\ntechnology\nfrom (\nselect \n-- select sum over all units\n$__timeGroupAlias(a.\"time\",'1h'),\nsum(\"ASSUME Actual dispatch\") as \"ASSUME Actual dispatch\",\ntechnology\nfrom\n(\n  -- select average per unit - remove duplicate sent data\n  SELECT\n  $__timeGroupAlias(time,'1h'),\n  avg(power) AS \"ASSUME Actual dispatch\",\n  unit_dispatch.simulation,\n  technology,\n  unit\nFROM unit_dispatch\njoin power_plant_meta c on unit = c.index and c.simulation=unit_dispatch.simulation\nwhere c.technology = 'hydro'\nand\n  $__timeFilter(time) AND\n  LOWER(unit_dispatch.simulation) = '$scenario'\nGROUP BY 1, unit_dispatch.simulation, c.technology, unit\nORDER BY 1) a\nGROUP BY 1, technology\n) a\nGROUP BY 1, technology"
    }
   ]
  },
  {
   "title": "Electricity Generation Conventional",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 }
  },
  {
   "title": "Lignite",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(index,1h),\n  (\"fossil_brown_coal/lignite\") AS \"ENTSO-E Data\"\nFROM entsoe.query_generation\nWHERE\n  $__timeFilter(index) AND\n  country = '$country_benchmark'\nORDER BY 1"
    },
    {
     "rawSql": "-- select average through time aggregation\nselect \n$__timeGroupAlias(a.\"time\",$__interval),\navg(\"ASSUME Actual dispatch\") as \"ASSUME Actual dispatch\",\ntechnology\nfrom (\nselect \n-- select sum over all units\n$__timeGroupAlias(a.\"time\",'1h'),\nsum(\"ASSUME Actual dispatch\") as \"ASSUME Actual dispatch\",\ntechnology\nfrom\n(\n  -- select average per unit - remove duplicate sent data\n  SELECT\n  $__timeGroupAlias(time,'1h'),\n  avg(power) AS \"ASSUME Actual dispatch\",\n  unit_dispatch.simulation,\n  technology,\n  unit\nFROM unit_dispatch\njoin power_plant_meta c on unit = c.index and c.simulation=unit_dispatch.simulation\nwhere c.technology = 'lignite'\nand\n  $__timeFilter(time) AND\n  LOWER(unit_dispatch.simulation) = '$scenario'\nGROUP BY 1, unit_dispatch.simulation, c.technology, unit\nORDER BY 1) a\nGROUP BY 1, technology\n) a\nGROUP BY 1, technology"
    }
   ]
  },
  {
   "title": "Nuclear",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(index,1h),\n  nuclear AS \"ENTSO-E Data\"\nFROM entsoe.query_generation\nWHERE\n  $__timeFilter(index) AND\n  country = '$country_benchmark'\nORDER BY 1"
    },
    {
     "rawSql": "select \n$__timeGroupAlias(a.\"time\",$__interval),\nsum(\"ASSUME Actual dispatch\") as \"ASSUME Actual dispatch\", \n--sum(\"AMIRIS Awarded Energy\"- \"ASSUME Actual dispatch\") as \"Difference\", \n--a.\"agent\",\nc.\"technology\"\nfrom\n(SELECT\n  time as \"time\",\n  avg(power) AS \"ASSUME Actual dispatch\",\n  SUBSTRING(unit,27) as \"agent\",\n  simulation,\n  unit\nFROM unit_dispatch\nWHERE\n  $__timeFilter(time) AND\n  LOWER(simulation) = '$scenario'\nGROUP BY 1, unit, power, simulation\nORDER BY 1) a\njoin power_plant_meta c on a.unit = c.index and c.simulation=a.simulation\nwhere c.technology like 'nuclear'\nGROUP BY 1, c.technology"
    }
   ]
  },
  {
   "title": "Oil",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(index,1h),\n  fossil_oil AS \"ENTSO-E Data\"\nFROM entsoe.query_generation\nWHERE\n  $__timeFilter(index) AND\n  country = '$country_benchmark'\nORDER BY 1"
    },
    {
     "rawSql": "select \n$__timeGroupAlias(a.\"time\",$__interval),\nsum(\"ASSUME Actual dispatch\") as \"ASSUME Actual dispatch\", \n--sum(\"AMIRIS Awarded Energy\"- \"ASSUME Actual dispatch\") as \"Difference\", \n--a.\"agent\",\nc.\"technology\"\nfrom\n(SELECT\n  time as \"time\",\n  avg(power) AS \"ASSUME Actual dispatch\",\n  SUBSTRING(unit,27) as \"agent\",\n  simulation,\n  unit\nFROM unit_dispatch\nWHERE\n  $__timeFilter(time) AND\n  LOWER(simulation) = '$scenario'\nGROUP BY 1, unit, power, simulation\nORDER BY 1) a\njoin power_plant_meta c on a.unit = c.index and c.simulation=a.simulation\nwhere c.technology like 'oil'\nGROUP BY 1, c.technology"
    }
   ]
  },
  {
   "title": "Hard Coal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(index,1h),\n  fossil_hard_coal AS \"ENTSO-E Data\"\nFROM entsoe.query_generation\nWHERE\n  $__timeFilter(index) AND\n  country = '$country_benchmark'\nORDER BY 1"
    },
    {
     "rawSql": "select \n$__timeGroupAlias(a.\"time\",$__interval),\nsum(\"ASSUME Actual dispatch\") as \"ASSUME Actual dispatch\", \n--sum(\"AMIRIS Awarded Energy\"- \"ASSUME Actual dispatch\") as \"Difference\", \n--a.\"agent\",\nc.\"technology\"\nfrom\n(SELECT\n  time as \"time\",\n  avg(power) AS \"ASSUME Actual dispatch\",\n  SUBSTRING(unit,27) as \"agent\",\n  simulation,\n  unit\nFROM unit_dispatch\nWHERE\n  $__timeFilter(time) AND\n  LOWER(simulation) = '$scenario'\nGROUP BY 1, unit, power, simulation\nORDER BY 1) a\njoin power_plant_meta c on a.unit = c.index and c.simulation=a.simulation\nwhere c.technology like 'hard coal'\nGROUP BY 1, c.technology"
    }
   ]
  },
  {
   "title": "Natural Gas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(index,1h),\n  fossil_gas AS \"ENTSO-E Data\"\nFROM entsoe.query_generation\nWHERE\n  $__timeFilter(index) AND\n  country = '$country_benchmark'\nORDER BY 1"
    },
    {
     "rawSql": "select \n$__timeGroupAlias(a.\"time\",$__interval),\nsum(\"ASSUME Actual dispatch\") as \"ASSUME Actual dispatch\", \n--sum(\"AMIRIS Awarded Energy\"- \"ASSUME Actual dispatch\") as \"Difference\", \n--a.\"agent\",\nc.\"technology\"\nfrom\n(SELECT\n  time as \"time\",\n  avg(power) AS \"ASSUME Actual dispatch\",\n  SUBSTRING(unit,27) as \"agent\",\n  simulation,\n  unit\nFROM unit_dispatch\nWHERE\n  $__timeFilter(time) AND\n  LOWER(simulation) = '$scenario'\nGROUP BY 1, unit, power, simulation\nORDER BY 1) a\njoin power_plant_meta c on a.unit = c.index and c.simulation=a.simulation\nwhere c.technology like 'gas'\nGROUP BY 1, c.technology"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "-- select average through time aggregation\nselect \n$__timeGroupAlias(a.\"time\",$__interval),\navg(\"ASSUME Actual dispatch\") as \"ASSUME Actual dispatch\",\ntechnology\nfrom (\nselect \n-- select sum over all units\n$__timeGroupAlias(a.\"time\",'1h'),\nsum(\"ASSUME Actual dispatch\") as \"ASSUME Actual dispatch\",\ntechnology\nfrom\n(\n  -- select average per unit - remove duplicate sent data\n  SELECT\n  $__timeGroupAlias(time,'1h'),\n  avg(power) AS \"ASSUME Actual dispatch\",\n  unit_dispatch.simulation,\n  technology,\n  unit\nFROM unit_dispatch\njoin power_plant_meta c on unit = c.index and c.simulation=unit_dispatch.simulation\nwhere c.technology like '%storage%'\nand\n  $__timeFilter(time) AND\n  LOWER(unit_dispatch.simulation) = '$scenario'\nGROUP BY 1, unit_dispatch.simulation, c.technology, unit\nORDER BY 1) a\nGROUP BY 1, technology\n) a\nGROUP BY 1, technology"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(index,1h),\n  hydro_pumped_storage AS \"ENTSO-E Data\"\nFROM entsoe.query_generation\nWHERE\n  $__timeFilter(index) AND\n  country = '$country_benchmark'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Installed Generation Capacities",
   "type": "piechart",
   "description": "Shows installed capacities in the simulation based on the fuel type",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  NOW() as time_sec,\n  SUM(max_power),\n  technology\nFROM power_plant_meta\nWHERE \"simulation\" LIKE '$scenario'\nGROUP BY technology, simulation;\n\n\n"
    }
   ]
  },
  {
   "title": "ENTSOE Mix",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  index AS \"time\",\n  biomass,\n  \"fossil_brown_coal/lignite\" as lignite,\n  \"fossil_coal-derived_gas\"+fossil_gas as gas,\n  fossil_hard_coal as hard_coal,\n  fossil_oil as oil,\n  --fossil_oil_shale,\n  --fossil_peat,\n  geothermal,\n  hydro_pumped_storage as hydro_storage,\n  \"hydro_run-of-river_and_poundage\" as hydro,\n  nuclear,\n  wind_offshore,\n  wind_onshore,\n  solar\nFROM entsoe.query_installed_generation_capacity\nWHERE\n  country = 'DE'\n  and index < $__timeTo() \nORDER BY 1"
    }
   ]
  },
  {
   "title": "ENTSO-E Comparison",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  index AS \"time\",\n  (biomass+solar+\"fossil_gas\"+\"fossil_brown_coal/lignite\"+\"fossil_oil\"+\"fossil_hard_coal\"+geothermal+other+waste+\"wind_offshore\"+\"wind_onshore\"+nuclear)*1e3 as total_entsoe\nFROM entsoe.query_generation\nWHERE\n  $__timeFilter(index) AND\n  country = 'DE'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  index AS \"time\",\n  nuclear*1e3 as nuclear,\n  \"fossil_hard_coal\"*1e3 as coal,\n  (\"hydro_run-of-river_and_poundage\"+hydro_water_reservoir)*1e3 as water,\n  biomass*1e3 as bio,\n  (\"fossil_coal-derived_gas\"+\"fossil_gas\")*1e3 as gas,\n  (fossil_oil+coalesce(fossil_oil_shale,0)+coalesce(fossil_peat,0)+\"fossil_brown_coal/lignite\")*1e3 as lignite,\n  (\"wind_offshore\"+\"wind_onshore\")*1e3 as wind,\n  solar*1e3 as solar,\n  (geothermal+other+waste)*1e3 as others\nFROM entsoe.query_generation\nWHERE\n  $__timeFilter(index) AND\n  country = 'DE'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Dispatch by technology",
   "type": "timeseries",
   "description": "Dispatch by technology",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "select time, sum(volume) as \"volume\", tech FROM \n(\nSELECT\n  $__timeGroupAlias(start_time,$__interval),\n  sum(accepted_volume) AS \"volume\", unit_id, pm.technology as tech\nFROM market_orders mo\njoin power_plant_meta pm on pm.index=mo.unit_id and pm.simulation=mo.simulation\nWHERE\n\n  $__timeFilter(start_time) AND\n  mo.simulation = '$scenario'\n\nGROUP BY 1, unit_id, bid_id, pm.technology\nORDER BY 1\n\n) a\ngroup by 1, tech\nORDER BY 1, tech desc"
    }
   ]
  },
  {
   "title": "Stromerzeugung $country_benchmark",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"index\",$__interval),\n  avg(biomass) as biomass,\n  avg(fossil_hard_coal) as fossil_hard_coal,\n  avg(geothermal) as geothermal,\n  avg(nuclear) as nuclear,\n  avg(\"fossil_brown_coal/lignite\") as \"fossil_brown_coal/lignite\",\n  avg(\"fossil_coal-derived_gas\") as \"fossil_coal-derived_gas\",\n  avg(\"hydro_run-of-river_and_poundage\") as \"hydro_run-of-river_and_poundage\",\n  avg(waste) as waste,\n  avg(solar) as solar,\n  avg(wind_offshore) as wind_offshore,\n  avg(wind_onshore) as wind_onshore,\n  avg(other_renewable) as other_renewable,\n  avg(hydro_water_reservoir) as hydro_water_reservoir,\n  avg(fossil_gas) as fossil_gas\nFROM entsoe.query_generation\nWHERE\n  $__timeFilter(index) AND\n  country = '$country_benchmark'\ngroup by 1\nORDER BY 1,2\n"
    }
   ]
  }
 ]
}